import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbarComponents/navbar";
import Footer from "./_components/footerComponents/footer";

const inter = Inter({ subsets: ["latin"] });

export async function generateMetadata(params, parrent) {
  // console.log(await parrent);
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " bg-gradient-to-tr from-blue-200 to-purple-200"
        }
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
